### ISSUE TITLE
Missing CancellationToken.AsTask() extension method

### ISSUE THREAD

**Issue by niemyjski** [StephenCleary/AsyncEx.Tasks#1]
We were using this and it seems to be missing and was pretty useful:

```csharp
public static Task WaitAsync(this AsyncManualResetEvent resetEvent, CancellationToken cancellationToken = default(CancellationToken)) {
    return Task.WhenAny(resetEvent.WaitAsync(), cancellationToken.AsTask());
}
```

**Comment by StephenCleary** [comment]
The `AsTask` method has been removed and is not coming back. This is due to a very subtle resource leak that can occur if the CT is long-lived. E.g., if the CT you're using is used over and over in `WaitAsync` calls, memory and resource use will grow.

I looked around for an issue describing this on the AsyncEx GH project but couldn't find it. It's possible this was raised over SO or email and never got an actual issue. Anyway, this resource leak is described [in the XML docs](https://github.com/StephenCleary/AsyncEx/blob/master/Source/Nito.AsyncEx%20(NET45%2C%20Win8%2C%20WP8%2C%20WPA81)/CancellationTokenExtensions.cs#L13) at least.

A leak-free approach is provided by the [`CancellationTokenTaskSource` type](https://github.com/StephenCleary/AsyncEx.Tasks/blob/master/src/Nito.AsyncEx.Tasks/CancellationTokenTaskSource.cs), which is similar to a `TaskCompletionSource` but coming from a `CancellationToken`. This type is used by the new [`Task.WaitAsync` extension method](https://github.com/StephenCleary/AsyncEx.Tasks/blob/master/src/Nito.AsyncEx.Tasks/TaskExtensions.cs#L14) (the `DoWaitAsync` implementation shows proper usage of the `CancellationTokenTaskSource` type).

Sorry, that was kind of long-winded. TL;DR version: you can use `Task.WaitAsync` instead:

    public static Task WaitAsync(this AsyncManualResetEvent resetEvent, CancellationToken cancellationToken = default(CancellationToken)) {
      return resetEvent.WaitAsync().WaitAsync(cancellationToken);
    }

The naming is a bit awkward: the first `WaitAsync` is asynchronously waiting for the MRE, and the second `WaitAsync` is asynchronously waiting for the first `WaitAsync`. :/  Also, the semantics will be different: this new implementation will return a canceled task if the CT is set, while the original would return a completed task (which seems dangerous).

As a final note, I'm still considering whether to add CT overloads to all the primitives. It's a pretty common request and point of some confusion. If I do, then they'll look just like this implementation.

**Comment by niemyjski** [comment]
Thanks for your explanation. We were initially doing a WhenAny because we didn't want to always wait for the first countdown event to finish. I'm pretty sure this will change that behavior from your sample and explanation. 

It would be a huge help if you took cancellationtokens. We find ourselves having to do this kind of stuff in more places than I'd like.
